// beginner/frontend/vue-ts-frontend/src/pages/authentication/Login.vue
<!-- copyright -->
<!-- https://jasonwatmore.com/post/2022/04/12/vue-3-veevalidate-form-validation-example-composition-api -->

<script setup lang="ts">
import { ref } from "vue";
import { Form, Field } from "vee-validate";
import * as Yup from "yup";
import { useRouter } from "vue-router";

import { authService } from "@/services/auth.service";
import { ILoginResponse } from "@/models/auth.model";
import { IError } from "@/models/base.model";
const router = useRouter();
import { useStore } from "@/store";

const email = ref("");
const password = ref("");

const schema = Yup.object().shape({
  email: Yup.string().email().required(),
  password: Yup.string().min(1).required(),
});

async function onSubmit() {
  await authService
    .login(email.value, password.value)
    .then(async (response: ILoginResponse) => {
      const { token } = response.data;
      localStorage.setItem(import.meta.env.VITE_TOKEN_NAME as string, token);

      useStore().$patch({
        token: token,
      });
      router.push("/");
    })
    .catch((err: IError) => {
      console.log(err);
      // setModal(true);
      // setModalMessage(getModalMessage("error", err));
    });
}
</script>
<template>
  <section class="min-h-screen flex items-center justify-center">
    <div class="container px-4 py-5 mx-auto md:flex md:items-center md:justify-center">
      <div class="md:w-8/12 lg:w-7/12 xl:w-6/12 md:pr-4">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg" class="w-full" alt="Phone image" />
      </div>
      <div class="md:w-8/12 xl:w-6/12 md:pl-4">
        <Form @submit="onSubmit" :validation-schema="schema" v-slot="{ errors }">
          <div class="mb-4">
            <Field
              name="email"
              placeholder="Email"
              v-model="email"
              type="text"
              class="w-full p-4 border border-gray-300 rounded-lg"
              :class="{ 'border-red-500': errors.email }"
            />
            <div class="text-red-500">{{ errors.email }}</div>
          </div>
          <div class="mb-4">
            <Field
              name="password"
              placeholder="Password"
              v-model="password"
              type="password"
              class="w-full p-4 border border-gray-300 rounded-lg"
              :class="{ 'border-red-500': errors.password }"
            />
            <div class="text-red-500">{{ errors.password }}</div>
          </div>

          <div class="flex justify-end items-center mb-4">
            <div class="text-end w-full md:w-1/2">
              <router-link to="/forgot-password"> Forgot password? </router-link>
            </div>
          </div>
          <div>
            <button type="submit" class="bg-blue-500 text-white font-bold py-2 px-4 rounded w-full">Sign in</button>
          </div>
        </Form>
      </div>
    </div>
  </section>
</template>

<style lang="scss" scoped></style>

// projects/nodejs-nextjs-mongodb/frontend/src/app/(auth)/login/page.tsx
"use client";
import { useEffect } from "react";
import { useRouter } from "next/navigation";

import { Button } from "@mui/material";
import TextField from "@mui/material/TextField";
import Link from "next/link";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import * as z from "zod";
import { loginSchema } from "@/zodSchema/loginSchema";
import { authService } from "@/services/auth.service";
import { getModalMessage } from "@/utils/helpers";
import { useGlobalContext } from "@/context/store";
type FormData = z.infer<typeof loginSchema>;

export default function Login() {
  const router = useRouter();
  const { setModal, setModalMessage } = useGlobalContext();

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm<FormData>({
    resolver: zodResolver(loginSchema),
  });
  useEffect(() => {
    reset({ email: "test@test.com", password: "test1234" });
  }, []);
  async function onSubmit(data: FormData) {
    await authService
      .login(data.email, data.password)
      .then(async (item: IUser) => {
        const { jwtToken } = item;
        localStorage.setItem(process.env.TOKEN_NAME as string, jwtToken);
        router.refresh();
        router.push("/dashboard");
      })
      .catch((err) => {
        setModal(true);
        setModalMessage(getModalMessage("error", err));
      });
  }
  return (
    <>
      <div className="light:bg-slate-100 dark:bg-none flex items-center justify-center h-screen">
        <div className="bg-white p-8 rounded-lg shadow-md shadow-slate-100 w-full sm:w-96">
          <h1 className="text-4xl text-center text-[#6E4895] font-semibold mb-6">LOGIN</h1>
          <form onSubmit={handleSubmit(onSubmit)}>
            <div className="mb-4">
              <label className="block text-gray-700 text-md font-bold mb-2">Email</label>
              <TextField {...register("email", { required: true })} id="email" type="email" variant="outlined" size="small" fullWidth />
              {errors?.email && <p className="text-red-600 text-sm">{errors?.email?.message}</p>}
            </div>
            <div className="mb-4">
              <label className="block text-gray-700 text-md font-bold mb-2">Password</label>

              <TextField
                {...register("password", { required: true })}
                id="password"
                type="password"
                variant="outlined"
                size="small"
                fullWidth
                // inputProps={{
                //   autoComplete: "new-password",
                // }}
              />
              {errors?.password && <p className="text-red-600 text-sm">{errors?.password?.message}</p>}
            </div>
            <div className="mb-4">
              <Button variant="contained" fullWidth className="text-xl font-bold" type="submit">
                Login
              </Button>
            </div>
          </form>
          <div className="mt-4 text-center">
            <p className="text-sm text-gray-600 font-bold">
              Don't have an account?{" "}
              <Link href="/register" className="text-indigo-500 hover:underline">
                Register
              </Link>
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
